version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fantasy_football_db
    environment:
      POSTGRES_DB: fantasy_football
      POSTGRES_USER: fantasy_user
      POSTGRES_PASSWORD: fantasy_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: