"""Initial migration - create player tables

Revision ID: ad6d72065edb
Revises: 
Create Date: 2025-07-24 23:48:48.222254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad6d72065edb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('position', postgresql.ENUM('QB', 'RB', 'WR', 'TE', 'K', 'DST', name='player_position'), nullable=False),
    sa.Column('team', postgresql.ENUM('ARI', 'ATL', 'BAL', 'BUF', 'CAR', 'CHI', 'CIN', 'CLE', 'DAL', 'DEN', 'DET', 'GB', 'HOU', 'IND', 'JAX', 'KC', 'LV', 'LAC', 'LAR', 'MIA', 'MIN', 'NE', 'NO', 'NYG', 'NYJ', 'PHI', 'PIT', 'SF', 'SEA', 'TB', 'TEN', 'WAS', name='nfl_team'), nullable=False),
    sa.Column('bye_week', sa.Integer(), nullable=True),
    sa.Column('nfl_id', sa.String(length=50), nullable=True),
    sa.Column('sleeper_id', sa.String(length=50), nullable=True),
    sa.Column('yahoo_id', sa.String(length=50), nullable=True),
    sa.Column('espn_id', sa.String(length=50), nullable=True),
    sa.Column('fantasypros_id', sa.String(length=50), nullable=True),
    sa.Column('consensus_rank_standard', sa.Integer(), nullable=True),
    sa.Column('consensus_rank_ppr', sa.Integer(), nullable=True),
    sa.Column('consensus_rank_half_ppr', sa.Integer(), nullable=True),
    sa.Column('avg_adp_standard', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_adp_ppr', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_adp_half_ppr', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('projected_points_standard', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('projected_points_ppr', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('projected_points_half_ppr', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('previous_year_points_standard', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('previous_year_points_ppr', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('previous_year_points_half_ppr', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_consensus_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fantasypros_players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=True),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=10), nullable=False),
    sa.Column('team', sa.String(length=10), nullable=False),
    sa.Column('fantasypros_id', sa.String(length=50), nullable=True),
    sa.Column('ecr_rank_standard', sa.Integer(), nullable=True),
    sa.Column('ecr_rank_ppr', sa.Integer(), nullable=True),
    sa.Column('ecr_rank_half_ppr', sa.Integer(), nullable=True),
    sa.Column('adp_standard', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('adp_ppr', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('adp_half_ppr', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('projected_points_standard', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('projected_points_ppr', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('projected_points_half_ppr', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('previous_year_points_standard', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('previous_year_points_ppr', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('previous_year_points_half_ppr', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('expert_count', sa.Integer(), nullable=True),
    sa.Column('position_rank', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_source_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fantasypros_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fantasypros_players')
    op.drop_table('players')
    # ### end Alembic commands ###
